development:
  # Sqlite Settings
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  
test:
  # Sqlite Settings
  # adapter: sqlite3
  # database: db/test.sqlite3
  # pool: 5
  # timeout: 5000
  
staging:
  adapter: mysql
  encoding: utf8
  database: hb_staging
  username: etandrib
  password: sqlluc1d1u5
  pool: 5
  
production:
  adapter: mysql
  encoding: utf8
  database: hb_production
  username: etandrib
  password: sqlluc1d1u5
  pool: 5