development:
  site_url: 'http://hbapp.local'
  site_name: "Heaven's Best Local Operators"
  admin_email: 'development@heavensbest.us'
  from_email: 'support@heavensbest.us'
  gateway: 'brain_tree'
  base_domain: 'heavensbest.us'
  require_payment_info_for_trials: 'true'
  random_query: 'RANDOM()'
  
test:
  <<: *non_production_settings

staging:
  site_url: 'http://staging.heavensbest.us'
  site_name: "Heaven's Best Local Operators"
  admin_email: 'staging@heavensbest.us'
  random_query: 'RAND()'
      
production:
  site_url: 'http://heavensbest.us'
  site_name: "Heaven's Best Local Operators"
  admin_email: 'info@heavensbest.us'
  from_email: 'support@heavensbest.us'
  gateway: 'brain_tree'
  base_domain: 'heavensbest.us'
  require_payment_info_for_trials: 'true'
  random_query: 'RAND()'
